language: cpp

compiler: gcc

addons: &gcc5
    apt:
        packages:
            - g++-5
        sources:
            - ubuntu-toolchain-r-test

before_script: cd tests

script:
    - make
    - ./toolbelt_tests
